<div class="ync_footer flex-container">
<footer>
    <br>
    <a href="index.php"><img src="images/Logo.png" alt="YNC logo icon"> </a>
    <aside id="footer-contact">
        <h3> &nbsp; &nbsp;Contact Us</h3>
        <ul class="contact_info">
            <li>YNC Tech</li>
            <li>John Street</li>
            <li>Hawthorn, Victoria, 3123</li>
            <li>Email: &nbsp; <a href="mailto:105179675@student.swin.edu.au">careers@yncgroup.com</a></li>
            <li><a href="https://swinburne.edu.au" target="_blank">All Rights Reserved &copy; YNC Tech </a></li>
        </ul>
    </aside>
</footer>
</div>
