<header>
    <div class="header-main-logo">
        <a href="index.php"><img src="images/Logo.png" alt="YNC logo icon"></a>
        <nav>
            <ul>
                <li><a href="index.php">HOME</a></li>
                <li><a href="jobs.php">JOBS</a></li>
                <li><a href="apply.php">APPLY NOW</a></li>
                <li><a href="about.php">ABOUT US</a></li>
                <li><a href="enhancements.php">ENHANCEMENTS</a></li>
            </ul>
        </nav>
    </div>
    <a href="mailto:104853318@student.swin.edu.au" class="contact-button">Contact Us</a>
</header>
